### ISSUE TITLE
In fastboard when trying to open youtube or browser in apps it's giving error

### ISSUE THREAD

**Issue by kush4545** [netless-io/fastboard#25]
The error is mentioned below:
[WindowManager]: create app error: Failed to fetch (This is on user side which is sharing fastboard)
and other user's side youtube or browser is not visible.

This is how we are inserting app:
 app.manager.addApp({
            kind: "Plyr",
            options: { title: "YouTube" },
            attributes: {
                src: "https://www.youtube.com",
                provider: "youtube",
            },
        });

**Comment by hyrious** [comment]
This was because the app `Plyr` is dynamically loaded through CDN links --
https://github.com/netless-io/fastboard/blob/35b23d37c6061b999bcba97a7dfb50db89ee6d30/packages/fastboard-core/src/behaviors/index.ts#L33-L35

and for some reason your network does not allow to fetch this URL.

There're 2 possible solutions to handle this case:

- Host the app's source code with another CDN or by yourself, for example you can choose to load app-plyr from https://unpkg.com/@netless/app-plyr@0.1.3/dist/main.iife.js. You can do that by calling the `register()` function right after you have imported fastboard:

  ```js
  import {register} from '@netless/fastboard'
  register({ kind: 'Plyr', src: 'https://unpkg.com/@netless/app-plyr@0.1.3/dist/main.iife.js' })
  ```

- Or, you can install @netless/app-plyr into your project, and register it directly.

  1. **Note**: Install the `^0.1.3` version, the 0.2 is for project Flat only.
  
     ```console
     npm add @netless/app-plyr@^0.1.3
     ```

  2. Register it right after you have imported fastboard:
  
     ```js
     import {register} from '@netless/fastboard'
     import Plyr from '@netless/app-plyr'
     register({ kind: 'Plyr', src: Plyr })
     ```

**Comment by kush4545** [comment]
hey @hyrious for youtube it's working fine now but for browser it's giving error
Is there any src change for embeded app?

**Comment by hyrious** [comment]
You can use this src:
https://unpkg.com/@netless/app-embedded-page@0.1.3/dist/main.iife.js

```js
register({
  kind: 'EmbeddedPage',
  src: 'https://unpkg.com/@netless/app-embedded-page@0.1.3/dist/main.iife.js'
})
```

**Comment by kush4545** [comment]
@hyrious thank you so much for help
