### ISSUE TITLE
How can we add pdf as app, in which we can put external pdf link and open the pdf in whiteboard 

### ISSUE THREAD

**Issue by kush4545** [netless-io/fastboard#28]
It is throwing and error scenes not defined

**Comment by hyrious** [comment]
PDF/PPT resources need to be [converted](https://docs.agora.io/en/interactive-whiteboard/reference/whiteboard-api/file-conversion?platform=web) first to enable them to be inserted to whiteboard. Static (PDF) resources become images while dynamic (PPT) resources become assets (json, image, audio and video, etc.), so that the corresponding frontend renderers know how to display them.

Once you get the conversion done, you can put the json response of [query conversion](https://docs.agora.io/en/interactive-whiteboard/reference/whiteboard-api/file-conversion?platform=web#query-to-be-converted-tasks) to this library to insert the document to whiteboard:

```js
fetch(`https://api.netless.link/v5/projector/tasks/${taskUUID}`)
  .then(r => r.ok && r.json())
  .then(response => {
    if (response && response.status == 'Finished')
      fastboard.insertDocs('a.pdf', response)
  })
```

**Comment by kush4545** [comment]
{
    "resp": {
        "error": {
            "title": "team not registration with uuid: lFsVUHd8EeyRoMGwMgqdqg",
            "messages": [],
            "requestId": "jMa0_B_S-wwwJw",
            "region": "us-sv",
            "traceStack": [
                "us-sv-shunt-api-65ddd5c87-rt2hn",
                "in-mum-shunt-api-7cd74fbc77-fflj4"
            ]
        }
    }
}

This is the response I am getting at the time of generating the task uuid 
I am using sdk token as req header and {resource and type} as body params
getting 200 as response but in response getting this message

**Comment by hyrious** [comment]
This means that your whiteboard project is not configured to provide conversion service in US. You need to enable them on the [console](https://console.agora.io/), in Project Config &rarr; Service Config &rarr; Whiteboard &rarr; Services.

**Comment by kush4545** [comment]
Thank you for reponse This is helpful and working fine
